package com.allscontractingdc.event;

public enum Event {
	SCHEDULE_ESTIMATE, MARK_AS_VISITED, SEND_ESTIMATE, BEGIN_WORK, FINISH_WORK, CREATE_INVOICE, SEND_INVOICE, RECEIVE_PAYMENT, FINISH_JOB
}
